# Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf

In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
print(scalar)
# Check the number of dimensions of a tensor
print(f'Dimensions: {scalar.ndim}')

tf.Tensor(7, shape=(), dtype=int32)
Dimensions: 0


In [3]:
# Create a vector
vector = tf.constant([10, 10])
print(f'Dimensions: {vector.ndim}')

Dimensions: 1


In [4]:
# Create a matrix
matrix = tf.constant([[10, 7], [7, 10]])
print(matrix)
print(f'Dimensions: {matrix.ndim}')

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
Dimensions: 2


In [5]:
# Create another matrix, specifying type
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16)
print(another_matrix)
print(f'Dimensions: {another_matrix.ndim}')

tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)
Dimensions: 2


In [6]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]],[[13, 14, 15],[16, 17, 18]]])
print(tensor)
print(f'Dimensions: {tensor.ndim}')

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
Dimensions: 3


#### Summary So Far
* Scalar: A single number
* Vector: A number with direction
* Matrix: A 2-dimensional array of numbers
* Tensor: An n-dimensional array of numbers

### Using tf.Variable()

In [7]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
print(changeable_tensor)
print(unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [8]:
# Try to change an element in changeable tensor
# changeable_tensor[0] = 7 # invalid
changeable_tensor[0].assign(7)

# Try to change unchangeable tensor
# unchangeable_tensor[0] = 7 # invalid
# unchangeable_tensor[0].assign(7) # invalid

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

🔑 **Note:** Usually do not have to worry about choosing between `tf.constant()` and `tf.Variable()`, TensorFlow will do it for you. However, if you need to create tensors, use `tf.constant()` and change if necessary.

### Creating Random Tensors

In [9]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # Set for reproducibility
random_1 = random_1.normal(shape=[3,2])
print(random_1)
random_2 = tf.random.Generator.from_seed(42) # Set for reproducibility
random_2 = random_2.normal(shape=[3,2])
print(random_2)

# Are they equal? 
print(random_1 == random_2)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ True  True]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)


### Shuffle the order of elements in a tensor

In [10]:
# Shuffle a tensor (valuable for shuffling data so inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])
print(not_shuffled)
print(f'Dimensions: {not_shuffled.ndim}')

# Shuffle our non_shuffled tensor
shuffled = tf.random.shuffle(not_shuffled)
print(shuffled)
print(f'Dimensions: {shuffled.ndim}') # Shuffled along first dimension

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)
Dimensions: 2
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)
Dimensions: 2


In [11]:
# Shuffle our non_shuffled tensor
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled, seed=42) # Derived from two seeds: global and operation level
print(shuffled)
print(f'Dimensions: {shuffled.ndim}') # Shuffled along first dimension

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)
Dimensions: 2


🛠 **Exercise:** Read through the TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed

### Other Ways to Make Tensors

In [12]:
# Create a tensor of all ones
tf.ones([10,7])

# Create a tensor of all zeroes
tf.zeros(shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

#### Turn NumPy Arrays into Tensors (tensors can be run on GPU)

In [13]:
# Can also turn NumPy arrays into TensorFlow tensors
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)

A = tf.constant(numpy_A)

numpy_A, A
# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # lowercase for vector

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

In [14]:
A = tf.constant(numpy_A, shape=(2, 3, 4)) # New tensor must have same number of elements as original tensor
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

### Getting Information from Tensors

When dealing with tensors, you want to be aware of the following attributes
* Shape
* Rank
* Axis or Dimension
* Size

In [15]:
# Create a rank 4 tensor (4 dimensions)
rank_4 = tf.zeros([2, 3, 4, 5])

rank_4.shape, rank_4.ndim, tf.size(rank_4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [16]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4.dtype)
print("Number of dimensions (rank):", rank_4.ndim)
print("Shape of tensor:", rank_4.shape)
print("Elements along zeroeth axis:", rank_4.shape[0])
print("Elements along last axis:", rank_4.shape[-1])
print("Total number of elements:", tf.size(rank_4).numpy()) # .numpy() makes pretty number instead of tf tensor type

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along zeroeth axis: 2
Elements along last axis: 5
Total number of elements: 120


### Indexing Tensors

Tensors can be indexed just like Python lists

In [17]:
# Get the first two elements of each dimension
rank_4[:2, :2, :2, :2]

# Get first element from each dimension from each index except final dimension
rank_4[:1, :1, :1, :] # : -> get whole thing

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [18]:
# Create a rank 2 tensor (2 dimensions)
rank_2 = tf.constant([[10, 7], [3, 4]])

# Get last item of each row
rank_2[:, -1]

# Add an extra dimension
rank_3 = rank_2[..., tf.newaxis] # ... spreads all axes 

# Alternative to newaxis
rank_3 = tf.expand_dims(rank_2, axis=-1) # -1 means expand final axis
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

### Manipulating Tensors (Tensor Operations)

**Basic Operations**

`+`,`-`,`*`,`/`

In [19]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7], [3, 4]])
tensor + 10 # Original tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [20]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [21]:
# Subtraction 
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [22]:
# We can use TensorFlow functions as well
tf.multiply(tensor, 10) # Using tensor functions is generally faster on GPUs than python operators

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

**Matrix Multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

**Two Rules**
* Inner dimensions must match
* Reuslting matrix will be the shape of the outer dimensions

In [23]:
# Matrix multiplication in TensorFlow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [24]:
A = tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]])
B = tf.constant([[3, 5], [6, 7], [1, 8]])
tf.matmul(A, B)
A @ B # Pythonic

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [25]:
# Create a (3, 2) tensor
X = tf.constant([[1, 2], [3, 4], [5, 6]])
# Create another (3, 2) tensor
Y = tf.constant([[7, 8], [9, 10], [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [26]:
# Try to multiply same dim (non-square) matrices
# tf.matmul(X, Y) # invalid

In [27]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [28]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [29]:
# Try to multiply X by reshaped Y
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [30]:
# Try using a reshaped X instead
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [31]:
# Can do the same with transpose
tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [32]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

**The Dot Product**

Matrix m ultiplication is also reffered to as the dot product. 

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [33]:
# Perform the dot product on X and Y (requires X *or* Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [34]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [35]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [36]:
# Check the values of Y, reshaped Y and transposed Y
print("Normal Y:\n", Y)
print("\nReshaped Y (2, 3):\n", tf.reshape(Y, shape=(2, 3)))
print("\nTransposed Y:\n", tf.transpose(Y))

Normal Y:
 tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)

Reshaped Y (2, 3):
 tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)

Transposed Y:
 tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.

### Changing the Datatype of a Tensor

In [37]:
# Create a new tensor with the default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [38]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [39]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [40]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

### Aggregating Tensors

Aggregating tensors = condensing them from  multiple values down to a smaller amount of values

In [41]:
# Get the absolute values
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

Let's go through the following forms of aggregation:
* Minimum
* Maximum
* Mean
* Sum

In [42]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([80, 38, 12, 86, 99, 88, 46, 84, 44, 57, 38, 39, 88, 34, 20, 50, 28,
       36, 41, 90,  3, 39, 15,  1, 15, 75, 39, 74, 82, 52, 13, 97, 15, 40,
       20, 80, 46, 95,  5, 60, 78, 67, 69, 36, 63, 32, 43, 56, 73, 63])>

In [43]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [44]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [45]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [46]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2544>

🛠 **Exercise:** With what we have just learned, find the variance and standard deviation of tensor E using TensorFlow methods.

In [47]:
# Find the variance
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=747.5856>

In [48]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32)) # Cast to avoid error of requiring "real or complex"

<tf.Tensor: shape=(), dtype=float32, numpy=27.34201>

### Find the Positional Maximum and Minimum

In [49]:
# Create a new tensor for finding positional maximum and minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [50]:
# Find the positional maximum
tf.argmax(F), F[tf.argmax(F)], tf.reduce_max(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [51]:
# Find the positional minimum
tf.argmin(F), F[tf.argmin(F)], tf.reduce_min(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

### Squeezing a Tensor (Removing all single dimensions)

In [52]:
# Create a tensor 
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [53]:
G.shape, tf.squeeze(G).shape

(TensorShape([1, 1, 1, 1, 50]), TensorShape([50]))

### One-hot Encoding Tensors

In [54]:
# Create a list of indicies
some_list = [0, 1, 2, 3] # Could be red, green, blue, purple

# One-hot encode our list of indicies
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [55]:
# Specify custom values for one-hot encoding
tf.one_hot(some_list, depth=4, on_value="ON", off_value="OFF")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>

### More TensorFlow Math Functions
* Squaring
* Log
* Square Root

In [56]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [57]:
# Square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [58]:
# Square Root (method requires float type)
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [59]:
# Log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays

In [60]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.,]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [61]:
# Convert tensor back to NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [62]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [63]:
J = tf.constant([3.])
J

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>

In [66]:
J.numpy()[0] # Access directly

3.0

In [67]:
# The default types of each are slightly differrent
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)